"""initial_schema

Revision ID: 6ea9d44aede3
Revises: 
Create Date: 2026-06-08 23:07:18.966343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6ea9d44aede3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=False),
    sa.Column('iso_code_2', sa.String(length=2), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('region', sa.String(length=80), nullable=False),
    sa.Column('is_developing', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iso_code_2')
    )
    op.create_index(op.f('ix_countries_iso_code'), 'countries', ['iso_code'], unique=True)
    op.create_index('ix_countries_region', 'countries', ['region'], unique=False)
    op.create_table('greenhouse_gases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('gwp_100', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_greenhouse_gases_symbol'), 'greenhouse_gases', ['symbol'], unique=True)
    op.create_table('sectors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sectors_name'), 'sectors', ['name'], unique=True)
    op.create_table('historical_emissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('ghg_id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('mtco2e', sa.Float(), nullable=False),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ghg_id'], ['greenhouse_gases.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_he_country_sector_year', 'historical_emissions', ['country_id', 'sector_id', 'year'], unique=False)
    op.create_index('ix_he_country_year', 'historical_emissions', ['country_id', 'year'], unique=False)
    op.create_index(op.f('ix_historical_emissions_country_id'), 'historical_emissions', ['country_id'], unique=False)
    op.create_index(op.f('ix_historical_emissions_ghg_id'), 'historical_emissions', ['ghg_id'], unique=False)
    op.create_index(op.f('ix_historical_emissions_sector_id'), 'historical_emissions', ['sector_id'], unique=False)
    op.create_index(op.f('ix_historical_emissions_year'), 'historical_emissions', ['year'], unique=False)
    op.create_table('ndc_submissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('submission_date', sa.Date(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('document_url', sa.Text(), nullable=True),
    sa.Column('unconditional_reduction_pct', sa.Float(), nullable=True),
    sa.Column('conditional_reduction_pct', sa.Float(), nullable=True),
    sa.Column('baseline_year', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ndc_country_target_year', 'ndc_submissions', ['country_id', 'target_year'], unique=False)
    op.create_index(op.f('ix_ndc_submissions_country_id'), 'ndc_submissions', ['country_id'], unique=False)
    op.create_index(op.f('ix_ndc_submissions_target_year'), 'ndc_submissions', ['target_year'], unique=False)
    op.create_table('emissions_targets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ndc_submission_id', sa.Integer(), nullable=False),
    sa.Column('sector_id', sa.Integer(), nullable=False),
    sa.Column('baseline_year', sa.Integer(), nullable=False),
    sa.Column('target_year', sa.Integer(), nullable=False),
    sa.Column('reduction_pct', sa.Float(), nullable=True),
    sa.Column('absolute_goal_mtco2e', sa.Float(), nullable=True),
    sa.Column('is_conditional', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ndc_submission_id'], ['ndc_submissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sector_id'], ['sectors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emissions_targets_ndc_submission_id'), 'emissions_targets', ['ndc_submission_id'], unique=False)
    op.create_index(op.f('ix_emissions_targets_sector_id'), 'emissions_targets', ['sector_id'], unique=False)
    op.create_index(op.f('ix_emissions_targets_target_year'), 'emissions_targets', ['target_year'], unique=False)
    op.create_index('ix_et_ndc_sector_year', 'emissions_targets', ['ndc_submission_id', 'sector_id', 'target_year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_et_ndc_sector_year', table_name='emissions_targets')
    op.drop_index(op.f('ix_emissions_targets_target_year'), table_name='emissions_targets')
    op.drop_index(op.f('ix_emissions_targets_sector_id'), table_name='emissions_targets')
    op.drop_index(op.f('ix_emissions_targets_ndc_submission_id'), table_name='emissions_targets')
    op.drop_table('emissions_targets')
    op.drop_index(op.f('ix_ndc_submissions_target_year'), table_name='ndc_submissions')
    op.drop_index(op.f('ix_ndc_submissions_country_id'), table_name='ndc_submissions')
    op.drop_index('ix_ndc_country_target_year', table_name='ndc_submissions')
    op.drop_table('ndc_submissions')
    op.drop_index(op.f('ix_historical_emissions_year'), table_name='historical_emissions')
    op.drop_index(op.f('ix_historical_emissions_sector_id'), table_name='historical_emissions')
    op.drop_index(op.f('ix_historical_emissions_ghg_id'), table_name='historical_emissions')
    op.drop_index(op.f('ix_historical_emissions_country_id'), table_name='historical_emissions')
    op.drop_index('ix_he_country_year', table_name='historical_emissions')
    op.drop_index('ix_he_country_sector_year', table_name='historical_emissions')
    op.drop_table('historical_emissions')
    op.drop_index(op.f('ix_sectors_name'), table_name='sectors')
    op.drop_table('sectors')
    op.drop_index(op.f('ix_greenhouse_gases_symbol'), table_name='greenhouse_gases')
    op.drop_table('greenhouse_gases')
    op.drop_index('ix_countries_region', table_name='countries')
    op.drop_index(op.f('ix_countries_iso_code'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
