import { useState } from 'react';
import { Link } from 'react-router-dom';
import { CheckCircle2, Download, FileCheck2, History } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { getFramework } from '@/data/classifications';
import { flattenSectors } from '@/lib/sector-classification';
import { areaKey, downloadFile, exportPackage, reviewCategory, reviseExercise, seriesCsv } from '@/lib/inventory-workspace';
import { Badge, Footer, Panel, type WorkspaceProps } from './shared';

export function InventoryReview({ exercise, update }: WorkspaceProps) {
  const [auditOpen, setAuditOpen] = useState(false);
  const [expanded, setExpanded] = useState<string | null>(null);
  const nodes = flattenSectors(getFramework(exercise.selection.frameworkId)!.hierarchy);
  const reviews = exercise.selection.selectedCodes.map(code => ({ code, label: nodes.find(n => n.code === code)?.label, ...reviewCategory(exercise, code) }));
  const complete = reviews.filter(r => r.complete).length;
  const openItems = reviews.filter(r => !r.complete).length + (exercise.reviewer.trim() && exercise.acknowledged ? 0 : 1);
  const canPrepare = reviews.length > 0 && complete === reviews.length && !!exercise.reviewer.trim() && exercise.acknowledged;
  const exportBasis = () => downloadFile('inventory-basis.csv', seriesCsv(reviews.flatMap(r => r.result.output.map(p => ({ exercise: exercise.name, sample: exercise.sample, country: exercise.countryCode, category: r.code, category_name: r.label, year: p.year, reported: r.result.reference.find(b => b.year === p.year)?.value, recalculated: p.value, unit: exercise.sources.find(s => s.id === 'collected')?.unit, measurement_basis: exercise.sources.find(s => s.id === 'collected')?.basis, method: r.config.method, applied: r.config.applied, focal_point: exercise.focalPoints[r.code], justification: r.config.justification })))), 'text/csv');
  const prepare = () => {
    if (!canPrepare) return;
    const next = reviseExercise(exercise, { status: 'ready' }, `Sign-off package prepared for ${exercise.reviewer}; compiler checks acknowledged`);
    update({ status: 'ready' }, `Sign-off package prepared for ${exercise.reviewer}; compiler checks acknowledged`);
    downloadFile('inventory-sign-off-package.json', JSON.stringify(exportPackage(next), null, 2));
  };
  return <>
    <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-primary">A traceable inventory</p><h2 className="font-display text-3xl font-semibold">Review & submit</h2><p className="mt-2 text-sm text-muted-foreground">Review the basis of every category and prepare the evidence for sign-off.</p></div><Button variant="outline" onClick={exportBasis}><Download className="mr-2 h-4 w-4" />Export inventory basis</Button></div>
    <div className="mb-5 grid grid-cols-2 gap-4 xl:grid-cols-4">{[{ label: 'Categories ready', value: `${complete} of ${reviews.length}`, hint: 'Basis, calculation & focal point' }, { label: 'Area assignments', value: `${reviews.reduce((s, r) => s + r.assigned, 0)} of ${reviews.reduce((s, r) => s + r.districts.length, 0)}`, hint: 'Across selected categories' }, { label: 'Reporting period', value: `${exercise.start}–${exercise.end}`, hint: `${reviews.filter(r => r.config.applied && r.config.method !== 'none').length} categories recalculated` }, { label: 'Open items', value: String(openItems), hint: 'Categories plus sign-off checks' }].map(metric => <Panel key={metric.label}><p className="text-xs font-medium text-muted-foreground">{metric.label}</p><p className="my-3 font-mono text-2xl font-semibold">{metric.value}</p><p className="text-xs text-muted-foreground">{metric.hint}</p></Panel>)}</div>
    <Panel><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-display text-xl font-semibold">Basis of every category</h3><p className="mt-1 text-xs text-muted-foreground">Sources, continuity and responsibility across the reporting period.</p></div>{exercise.sample && <Badge>Sample values</Badge>}</div>
      <div className="overflow-x-auto"><table className="w-full min-w-[880px] text-left text-sm"><thead className="border-b text-xs uppercase text-muted-foreground"><tr>{['Category', 'Series used', `History ${exercise.start} → ${exercise.end}`, 'Areas', 'Recalc.', 'Status', 'Focal point'].map(label => <th scope="col" className="px-2 pb-3 font-medium" key={label}>{label}</th>)}</tr></thead><tbody>{reviews.map(r => {
        const ids = [...new Set(r.districts.map(d => exercise.assignments[areaKey(r.code, d)]).filter(Boolean))];
        return <tr className="border-b last:border-0" key={r.code}><td className="max-w-52 px-2 py-4"><button className="text-left hover:text-primary hover:underline" onClick={() => setExpanded(expanded === r.code ? null : r.code)}><span className="mr-2 font-mono text-xs text-muted-foreground">{r.code}</span>{r.label}</button></td><td className="max-w-44 px-2 text-xs text-muted-foreground">{ids.map(id => id === 'mix' ? 'Entry mix' : exercise.sources.find(s => s.id === id)?.name ?? 'Source unavailable').join(' + ') || 'Not assigned yet'}</td><td className="px-2"><div className="flex h-2.5 min-w-32 overflow-hidden rounded-full bg-muted" aria-label={`${r.result.output.filter(p => p.value !== null).length} of ${r.result.output.length} years with estimates`}>{r.result.output.map(p => <span title={`${p.year}: ${p.value == null ? 'missing' : p.value.toFixed(3)}`} key={p.year} className={p.value == null ? 'bg-muted' : r.config.method !== 'none' && r.config.applied ? 'bg-primary' : 'bg-[#a4643b]'} style={{ width: `${100 / r.result.output.length}%` }} />)}</div></td><td className="px-2 font-mono text-xs">{r.assigned}/{r.districts.length}</td><td className="px-2 text-xs">{r.config.applied ? r.config.method === 'none' ? 'Retained' : r.config.method : 'Pending'}</td><td className="px-2"><Badge tone={r.complete ? 'good' : 'warn'}>{r.complete ? 'Complete' : 'In progress'}</Badge></td><td className="w-44 px-2"><Input aria-label={`Focal point for ${r.code}`} placeholder="Name / institution" value={exercise.focalPoints[r.code] ?? ''} onChange={e => update({ focalPoints: { ...exercise.focalPoints, [r.code]: e.target.value } })} /></td></tr>;
      })}</tbody></table></div>
      {expanded && (() => { const r = reviews.find(r => r.code === expanded)!; return <div className="mt-5 rounded-xl bg-muted/40 p-4"><h4 className="text-sm font-semibold">{r.code} · {r.label}</h4>{r.issues.length ? <ul className="mt-2 list-disc space-y-1 pl-5 text-xs text-muted-foreground">{r.issues.map(issue => <li key={issue}>{issue}</li>)}</ul> : <p className="mt-2 text-xs text-primary">All readiness checks passed.</p>}<p className="mt-3 whitespace-pre-wrap text-xs text-muted-foreground">{r.config.justification || 'No methodology justification yet.'}</p><div className="mt-3 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => update({ activeCategory: r.code, step: 2 })}>Review sources</Button><Button size="sm" variant="outline" onClick={() => update({ activeCategory: r.code, step: 3 })}>Review calculation</Button></div></div>; })()}
    </Panel>
    {complete > 0 && <div className="mt-4 flex justify-end"><Button asChild variant="outline"><Link to={`/scenario-analysis?exercise=${encodeURIComponent(exercise.id)}`}>Build a scenario from this inventory →</Link></Button></div>}
    <div className="my-4 flex flex-wrap items-start justify-between gap-4"><div className="flex-1 text-xs text-muted-foreground"><p className="font-medium">Source versions pinned to this exercise</p>{exercise.sources.map(s => <p className="mt-1" key={s.id}>{s.name} · {s.version} · {s.rows.length} observations · imported {new Date(s.importedAt).toLocaleDateString()}</p>)}</div><Button variant="link" onClick={() => setAuditOpen(!auditOpen)}><History className="mr-2 h-4 w-4" />{auditOpen ? 'Close audit trail' : 'Open audit trail'}</Button></div>
    {auditOpen && <Panel className="mb-5"><h3 className="mb-4 font-semibold">Exercise history</h3><ol className="max-h-72 space-y-3 overflow-y-auto">{[...exercise.audit].reverse().map((event, i) => <li key={i} className="border-l-2 border-primary/20 pl-3"><time className="text-xs text-muted-foreground">{new Date(event.at).toLocaleString()}</time><p className="mt-1 text-sm">{event.action}</p></li>)}</ol><p className="mt-4 text-xs text-muted-foreground">Local change history; this is not a signed or tamper-proof audit record.</p></Panel>}
    <Panel><div className="flex items-start gap-3"><FileCheck2 className="mt-1 h-5 w-5 text-primary" /><div className="flex-1"><h3 className="font-semibold">Prepare for sign-off</h3><p className="mt-2 text-sm leading-relaxed text-muted-foreground">Download a package containing source observations, district decisions, officer notes, recalculation results and change history. Share it with your reviewer through your institution’s reporting process.</p><label className="mt-4 block max-w-md text-sm">Reviewer / institution<Input className="mt-2" placeholder="Who will review this inventory?" value={exercise.reviewer} onChange={e => update({ reviewer: e.target.value })} /></label><label className="mt-4 flex items-start gap-2 text-sm"><input type="checkbox" checked={exercise.acknowledged} className="mt-1 accent-primary" onChange={e => update({ acknowledged: e.target.checked, status: 'draft' }, e.target.checked ? 'Compiler acknowledged source, scope and methodology checks' : 'Compiler checks reopened')} />I have reviewed source boundaries, units, missing data and methodology assumptions for every selected category.</label><p className="mt-3 text-xs text-muted-foreground">Saved in this browser. Preparing a package records readiness locally; it does not send or submit data to an external authority.</p>{exercise.status === 'ready' && <p role="status" className="mt-4 flex items-center gap-2 text-sm text-primary"><CheckCircle2 className="h-4 w-4" />Sign-off package prepared for {exercise.reviewer}.</p>}</div></div></Panel>
    <Footer back="Recalculation" onBack={() => update({ step: 3 })} next="Prepare sign-off package" onNext={prepare} disabled={!canPrepare}>{openItems ? `${openItems} open items — open category rows to resolve them` : 'Ready for your reviewer'}</Footer>
  </>;
}
