/**
 * Applies the user-selected deterministic recalculation method and records the choice in the exercise audit trail.
 *
 * Read the owning guide before changing source, unit, authentication, or availability rules.
 */
import { number, seriesColors } from '@/lib/inventory-presentation';
import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { areaKey, defaultRecalculation, districtsFor, recalculate, type Recalculation as Config } from '@/lib/inventory-workspace';
import { Badge, CategoryPicker, Footer, NumberField, Panel, type WorkspaceProps } from './shared';
import { InventoryChart } from './InventoryChart';
import { SourceImport } from './SourceImport';

const methods: { id: Config['method']; title: string; description: string }[] = [
  { id: 'none', title: 'Keep collected basis', description: 'Retain the reported series when all reporting areas use collected data.' },
  { id: 'overlap', title: 'Overlap', description: 'Apply the mean new/old ratio from at least three paired years to earlier collected estimates.' },
  { id: 'surrogate', title: 'Surrogate data', description: 'Scale a documented indicator to the new estimate in the source-change year.' },
  { id: 'interpolation', title: 'Interpolation', description: 'Fill internal gaps between known new-basis estimates. No extrapolation beyond known years.' },
  { id: 'full', title: 'Full recalculation', description: 'Use your imported, independently recalculated estimates for every historical year.' },
];
export function Recalculation({ exercise, update }: WorkspaceProps) {
  const [importOpen, setImportOpen] = useState(false);
  const category = exercise.activeCategory;
  const config = exercise.recalculations[category] ?? defaultRecalculation(exercise);
  const result = recalculate(exercise, category, config);
  const districts = districtsFor(exercise, category);
  const assignmentsComplete = districts.length > 0 && districts.every(d => !!exercise.assignments[areaKey(category, d)]);
  const setConfig = (patch: Partial<Config>) => update({ recalculations: { ...exercise.recalculations, [category]: { ...config, ...patch, applied: false } } });
  const delta = (index: number) => { const before = result.reference[index]?.value, after = result.output[index]?.value; return before != null && before !== 0 && after != null ? (after - before) / Math.abs(before) * 100 : null; };
  const trend = (points: typeof result.output) => points[0]?.value && points[points.length - 1]?.value != null ? 100 * (points[points.length - 1].value! - points[0].value!) / Math.abs(points[0].value!) : null;
  const apply = () => update({ recalculations: { ...exercise.recalculations, [category]: { ...config, applied: true } } }, `${category}: applied ${config.method}, ${config.start}–${config.change - 1}; ${config.justification}`);
  return <>
    <div className="mb-6"><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-primary">Keep the history comparable</p><h2 className="font-display text-3xl font-semibold">Recalculation</h2><p className="mt-2 text-sm text-muted-foreground">Preview how a change of source affects the base year and the reported trend.</p></div>
    <Panel className="mb-5"><div className="flex flex-wrap items-end justify-between gap-4"><CategoryPicker exercise={exercise} update={update} /><div className="flex flex-wrap items-center gap-3"><Badge tone={config.applied ? 'good' : 'warn'}>{config.applied ? 'Calculation applied' : 'Calculation needs review'}</Badge><span className="text-xs text-muted-foreground">{districts.length} reporting areas · {exercise.sources.find(s => s.id === 'collected')?.unit}</span></div></div></Panel>
    <div className="grid items-start gap-5 xl:grid-cols-[310px_minmax(0,1fr)]"><aside className="space-y-4"><Panel><h3 className="font-display text-xl font-semibold">Splicing method</h3><p className="mb-4 mt-2 text-xs text-muted-foreground">How earlier years are placed on the new basis.</p><div className="space-y-2" role="radiogroup" aria-label="Splicing method">{methods.map(method => <label key={method.id} className={`flex cursor-pointer items-start gap-3 rounded-xl border p-3 ${config.method === method.id ? 'border-primary bg-primary/5' : ''}`}><input className="mt-1 accent-primary" type="radio" name="method" checked={config.method === method.id} onChange={() => setConfig({ method: method.id })} /><span><span className="text-sm font-semibold">{method.title}</span><span className="mt-1 block text-xs leading-relaxed text-muted-foreground">{method.description}</span></span></label>)}</div></Panel>
      {config.method !== 'none' && <Panel><h3 className="mb-4 text-sm font-semibold">Range & assumptions</h3><div className="grid grid-cols-2 gap-3">{[{ key: 'start', label: 'Recalculate from' }, { key: 'change', label: 'Source-change year' }, ...(config.method === 'overlap' ? [{ key: 'overlapStart', label: 'Overlap from' }, { key: 'overlapEnd', label: 'Overlap through' }] : [])].map(field => <NumberField key={field.key} label={field.label} value={config[field.key]} min={exercise.start} max={exercise.end} onCommit={v => setConfig({ [field.key]: v })} />)}</div><label className="mt-4 flex items-start gap-2 text-xs leading-relaxed"><input type="checkbox" checked={config.includeBase} className="mt-0.5 accent-primary" onChange={e => setConfig({ includeBase: e.target.checked })} />Include all years back to the base year ({exercise.start}) so the target stays comparable.</label>{config.method === 'surrogate' && <Button className="mt-3" variant="outline" onClick={() => setImportOpen(true)}>Import surrogate indicator</Button>}</Panel>}
      <a className="block px-1 text-xs text-primary underline underline-offset-4" target="_blank" rel="noreferrer" href="https://www.ipcc-nggip.iges.or.jp/public/2006gl/pdf/1_Volume1/V1_5_Ch5_Timeseries.pdf">IPCC guidance: time-series consistency ↗</a>
    </aside><div className="min-w-0 space-y-4"><Panel><div className="mb-4 flex items-center justify-between"><h3 className="font-display text-xl font-semibold">Before and after</h3>{exercise.sample && <Badge>Sample values</Badge>}</div><InventoryChart change={config.method === 'none' ? undefined : config.change} unit={exercise.sources.find(s => s.id === 'collected')?.unit} series={[{ id: 'collected', name: 'As reported', color: seriesColors.collected, points: result.reference }, { id: 'output', name: 'Recalculated preview', color: seriesColors.output, points: result.output }]} />{config.method === 'overlap' && <p className="mt-3 text-xs text-muted-foreground">Mean overlap ratio: {number(result.factor, 4)} · paired years: {result.overlapYears.join(', ') || 'none'}. Confirm that the relationship between sources is stable before applying.</p>}</Panel>
      <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{ label: `Base year ${exercise.start}`, value: delta(0), hint: 'vs as reported' }, { label: `Latest year ${exercise.end}`, value: delta(result.output.length - 1), hint: 'vs as reported' }, { label: `Trend ${exercise.start}–${exercise.end}`, value: trend(result.output), hint: `was ${number(trend(result.reference), 1)}%` }].map(metric => <Panel className="!p-4" key={metric.label}><p className="text-xs text-muted-foreground">{metric.label}</p><p className="my-2 font-mono text-xl font-semibold">{metric.value == null ? '—' : `${number(metric.value, 1)}%`}</p><p className="text-xs text-muted-foreground">{metric.hint}</p></Panel>)}<Panel className="!p-4"><p className="text-xs text-muted-foreground">Coverage</p><p className="my-2 text-lg font-semibold text-primary">{result.output.filter(p => p.value !== null).length}/{result.output.length} years</p><p className="text-xs text-muted-foreground">{result.partial ? 'Mixed historical basis' : 'Review method consistency'}</p></Panel></div>
      <Panel><label className="text-sm font-semibold">Justification for the inventory report<textarea className="mt-3 min-h-28 w-full rounded-xl border bg-background p-3 text-sm font-normal" placeholder="Why the source changed, method assumptions, overlap evidence, and implications for the base year…" value={config.justification} onChange={e => setConfig({ justification: e.target.value })} /></label><Button variant="link" className="px-0 text-xs" onClick={() => { const notes = Object.entries(exercise.notes).filter(([key, note]) => { try { return JSON.parse(key)[0] === category && note.trim(); } catch { return false; } }).map(([key, note]) => `${JSON.parse(key).slice(1).join(' · ')}: ${note}`); setConfig({ justification: [config.justification, ...notes].filter(Boolean).join('\n') }); }} disabled={!Object.keys(exercise.notes).length}>Append officer notes</Button></Panel>
      {(result.errors.length > 0 || !assignmentsComplete || result.partial) && <Panel className="border-border"><h3 className="text-sm font-semibold">Resolve before review</h3><ul className="mt-3 list-disc space-y-2 pl-5 text-xs text-muted-foreground">{!assignmentsComplete && <li>Assign a source to every reference reporting area in Time series.</li>}{result.errors.map(error => <li key={error}>{error}</li>)}{result.partial && <li>Some earlier years retain the old basis. Include the base year to make the full reporting period comparable.</li>}</ul></Panel>}
      <div className="flex justify-end"><Button onClick={apply} disabled={!assignmentsComplete || !!result.errors.length || result.partial || config.applied}>{config.applied ? 'Calculation applied' : 'Apply recalculation'}</Button></div>
    </div></div>
    <Footer back="Time series & source mix" onBack={() => update({ step: 2 })} next="Review inventory basis" onNext={() => update({ step: 4 })}>Review all selected categories before preparing sign-off.</Footer>
    <SourceImport exercise={exercise} update={update} open={importOpen} onOpenChange={setImportOpen} />
  </>;
}
