/**
 * Compares collected and candidate annual series with transparent coverage and fit statistics.
 *
 * Read the owning guide before changing source, unit, authentication, or availability rules.
 */
import { number, seriesColors, downloadChart } from '@/lib/inventory-presentation';
import { useEffect, useState } from 'react';
import { CheckCircle2, Download, Plus, SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { areaKey, bestSource, districtsFor, downloadFile, passes, seriesCsv, sourceSeries, statistics, type SourceId, yearsIn } from '@/lib/inventory-workspace';
import { Badge, CategoryPicker, Footer, NumberField, Panel, Select, type WorkspaceProps } from './shared';
import { InventoryChart } from './InventoryChart';
import { SourceImport } from './SourceImport';
import { EntryReview } from './EntryReview';

export function TimeSeries({ exercise, update }: WorkspaceProps) {
  const [view, setView] = useState<'national' | 'district'>('national');
  const [importOpen, setImportOpen] = useState(false);
  const [thresholdsOpen, setThresholdsOpen] = useState(false);
  const [mode, setMode] = useState<'series' | 'residuals' | 'scatter'>('series');
  const [search, setSearch] = useState('');
  const [onlyReview, setOnlyReview] = useState(false);
  const [sort, setSort] = useState('worst');
  const [entryDistrict, setEntryDistrict] = useState<string | null>(null);
  const [visible, setVisible] = useState<SourceId[]>(['a', 'b']);
  useEffect(() => { document.getElementById('main-content')?.scrollTo({ top: 0 }); }, [entryDistrict]);
  const category = exercise.activeCategory;
  const districts = districtsFor(exercise, category);
  const reference = sourceSeries(exercise, 'collected', category);
  const collected = exercise.sources.find(s => s.id === 'collected');
  const candidates = exercise.sources.filter(s => s.id === 'a' || s.id === 'b');
  const stats = candidates.map(s => {
    const national = statistics(reference, sourceSeries(exercise, s.id, category));
    const passing = districts.filter(d => passes(statistics(sourceSeries(exercise, 'collected', category, d), sourceSeries(exercise, s.id, category, d)), exercise.thresholds)).length;
    return { source: s, ...national, passing, eligible: passes(national, exercise.thresholds) && !!districts.length && passing / districts.length * 100 >= exercise.thresholds.coverage };
  });
  const best = stats.filter(s => s.eligible).sort((a, b) => a.mape! - b.mape!)[0];
  const assigned = districts.filter(d => !!exercise.assignments[areaKey(category, d)]).length;
  const seriesFor = (district?: string) => exercise.sources.filter(s => s.id === 'collected' || visible.includes(s.id as SourceId)).sort((a, b) => ['collected', 'a', 'b'].indexOf(a.id) - ['collected', 'a', 'b'].indexOf(b.id)).map(s => ({ id: s.id, name: s.name, color: seriesColors[s.id as SourceId], points: sourceSeries(exercise, s.id, category, district) }));
  function assignAll(id?: SourceId) {
    const assignments = { ...exercise.assignments };
    districts.forEach(d => { assignments[areaKey(category, d)] = id ?? bestSource(exercise, category, d); });
    update({ assignments }, `${category}: ${id ? `assigned all reporting areas to ${exercise.sources.find(s => s.id === id)?.name}` : 'auto-assigned best passing source; collected retained where no candidate passed'}`);
  }
  const districtRows = districts.map(district => {
    const reference = sourceSeries(exercise, 'collected', category, district);
    const matches = candidates.map(s => ({ id: s.id as SourceId, stats: statistics(reference, sourceSeries(exercise, s.id, category, district)) }));
    const good = matches.some(s => passes(s.stats, exercise.thresholds));
    return { district, matches, good, score: Math.min(...matches.map(s => s.stats.mape ?? Infinity)), choice: exercise.assignments[areaKey(category, district)] };
  }).filter(d => d.district.toLowerCase().includes(search.toLowerCase()) && (!onlyReview || !d.good || !d.choice)).sort((a, b) => sort === 'name' ? a.district.localeCompare(b.district) : b.score - a.score || a.district.localeCompare(b.district));
  if (entryDistrict) return <EntryReview exercise={exercise} update={update} district={entryDistrict} onBack={() => setEntryDistrict(null)} />;
  return <>
    <div className="mb-4 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-xs font-semibold uppercase tracking-widest text-primary">Compare & choose</p><h2 className="font-display text-2xl font-semibold">Time series</h2><p className="mt-2 text-sm text-muted-foreground">Build a defensible inventory basis, one reporting area at a time.</p></div><Button variant="outline" onClick={() => setImportOpen(true)}><Plus className="mr-2 h-4 w-4" />Import data source</Button></div>
    <Panel className="mb-4 !py-3"><div className="flex flex-wrap items-end justify-between gap-4"><div className="flex gap-1 rounded-xl bg-muted p-1" aria-label="Comparison view"><Button variant={view === 'national' ? 'secondary' : 'ghost'} aria-pressed={view === 'national'} onClick={() => setView('national')}>National</Button><Button variant={view === 'district' ? 'secondary' : 'ghost'} aria-pressed={view === 'district'} onClick={() => setView('district')}>By district</Button></div><div className="max-w-full sm:max-w-sm"><CategoryPicker exercise={exercise} update={update} /></div><div className="flex gap-3">{(['start', 'end'] as const).map(key => <div className="w-24" key={key}><NumberField label={key === 'start' ? 'Period start' : 'Period end'} value={exercise[key]} min={key === 'start' ? 1900 : exercise.start} max={key === 'start' ? exercise.end : 2200} onCommit={value => update({ [key]: value }, `Changed comparison ${key} to ${value}`)} /></div>)}</div></div></Panel>
    {!collected ? <Panel className="py-16 text-center"><div className="mx-auto mb-4 w-fit rounded-2xl bg-primary/10 p-4"><Plus className="h-7 w-7 text-primary" /></div><h3 className="text-xl font-semibold">Start with your collected reference</h3><p className="mx-auto my-3 max-w-lg text-sm leading-relaxed text-muted-foreground">Import annual observations for your selected categories, then add up to two candidate sources. Your charts, fit statistics and coverage checks will be calculated from those files.</p><Button className="mt-3" onClick={() => setImportOpen(true)}>Import collected data</Button></Panel> : view === 'national' ? <div className="grid items-start gap-5 xl:grid-cols-[280px_minmax(0,1fr)]">
      <aside className="space-y-4"><Panel className="border-[#a4643b]/30 bg-[#a4643b]/5"><span className="text-xs font-semibold uppercase tracking-wider text-[#a4643b]">Reference</span><h3 className="mt-2 font-semibold">{collected.name}</h3><p className="mt-2 text-xs text-muted-foreground">{collected.version}</p><p className="mt-2 text-xs text-muted-foreground">{collected.unit} · {districts.length} reporting areas</p><p className="mt-1 text-xs text-muted-foreground">{collected.basis}</p></Panel>
        <div className="flex justify-between text-xs font-semibold uppercase tracking-wider text-muted-foreground"><span>Candidate series</span><span>{candidates.length} of 2</span></div>
        {candidates.map(s => <label key={s.id} className={`flex cursor-pointer gap-3 rounded-xl border bg-card p-4 ${visible.includes(s.id as SourceId) ? 'border-primary/50 ring-1 ring-primary/10' : ''}`}><input type="checkbox" aria-label={`Show ${s.name}`} className="mt-1 accent-primary" checked={visible.includes(s.id as SourceId)} onChange={e => setVisible(e.target.checked ? [...visible, s.id as SourceId] : visible.filter(id => id !== s.id))} /><span className="min-w-0"><span className="block text-sm font-semibold">{s.name}</span><span className="mt-1 block text-xs text-muted-foreground">{s.version}</span><span className="mt-1 block text-xs text-muted-foreground">{s.unit} · {districts.filter(d => sourceSeries(exercise, s.id, category, d).some(p => p.value !== null)).length}/{districts.length} areas with data</span></span></label>)}
        {candidates.length < 2 && <Button variant="outline" className="h-12 w-full border-dashed" onClick={() => setImportOpen(true)}><Plus className="mr-2 h-4 w-4" />Add a candidate source</Button>}
        <Panel><div className="flex items-center justify-between gap-2"><h3 className="text-sm font-semibold">Substitution thresholds</h3><button aria-label="Edit thresholds" onClick={() => setThresholdsOpen(!thresholdsOpen)} className="rounded p-2 "><SlidersHorizontal className="h-4 w-4" /></button></div><dl className="mt-4 space-y-3 text-xs">{[{ key: 'r2', label: 'R²', prefix: '≥', max: 1, step: .01 }, { key: 'mape', label: 'MAPE', prefix: '≤', max: undefined, step: .5 }, { key: 'bias', label: 'Absolute bias', prefix: '≤', max: undefined, step: .5 }, { key: 'coverage', label: 'Coverage', prefix: '≥', max: 100, step: 1 }].map(t => <div className="flex items-center justify-between gap-3" key={t.key}><dt className="text-muted-foreground">{t.label}</dt><dd>{thresholdsOpen ? <Input aria-label={`${t.label} threshold`} type="number" className="h-8 w-20" min={0} max={t.max} step={t.step} value={exercise.thresholds[t.key]} onChange={e => { const v = Number(e.target.value); if (Number.isFinite(v) && v >= 0 && (t.max === undefined || v <= t.max)) update({ thresholds: { ...exercise.thresholds, [t.key]: v } }, `Changed ${t.label} threshold to ${v}`); }} /> : <span className="font-mono">{t.prefix} {exercise.thresholds[t.key]}{t.key !== 'r2' ? '%' : ''}</span>}</dd></div>)}</dl><p className="mt-4 text-xs leading-relaxed text-muted-foreground">Exercise-specific screening rules. Coverage checks paired years and passing districts; thresholds are not an official approval standard.</p></Panel>
      </aside>
      <div className="min-w-0 space-y-4"><Panel><div className="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-semibold">Candidates vs collected data</h3><p className="mt-1 text-xs text-muted-foreground">{category} · sum of {districts.length} reference reporting areas · {collected.unit}</p></div>{exercise.sample && <Badge>Sample values</Badge>}</div><div id="inventory-national-chart"><InventoryChart series={seriesFor()} mode={mode} unit={collected.unit} /></div><div className="mt-4 flex flex-wrap gap-2 border-t pt-3">{(['series', 'residuals', 'scatter'] as const).map(m => <Button key={m} variant={mode === m ? 'secondary' : 'ghost'} size="sm" onClick={() => setMode(m)}>{m === 'series' ? 'Time series' : m === 'residuals' ? 'Residuals' : 'Scatter vs collected'}</Button>)}<Button variant="ghost" size="sm" onClick={() => downloadFile('series-comparison.csv', seriesCsv(yearsIn(exercise.start, exercise.end).map(year => Object.fromEntries([['year', year], ...seriesFor().map(s => [`${s.id}: ${s.name}`, s.points.find(p => p.year === year)?.value])]))), 'text/csv')}><Download className="mr-2 h-3 w-3" />Export data</Button><Button variant="ghost" size="sm" onClick={() => downloadChart('inventory-national-chart', `${exercise.sample ? 'SAMPLE · ' : ''}${category} · ${exercise.start}–${exercise.end} · ${collected.unit} · ${mode}`, seriesFor())}>Export chart</Button></div></Panel>
        <div className="grid grid-cols-2 gap-3 lg:grid-cols-4">{[{ title: 'R² vs collected', key: 'r2', suffix: '', digits: 3 }, { title: 'MAPE', key: 'mape', suffix: '%', digits: 1 }, { title: 'Mean bias', key: 'bias', suffix: '%', digits: 1 }, { title: 'Districts passing', key: 'passing', suffix: '', digits: 0 }].map(metric => <Panel className="!p-4" key={metric.key}><h4 className="mb-3 text-xs font-semibold text-muted-foreground">{metric.title}</h4>{stats.length ? stats.map(s => <div key={s.source.id} className="mt-2 flex items-center justify-between gap-2"><span className="text-xs text-muted-foreground">Series {s.source.id.toUpperCase()}</span><strong className={`font-mono text-lg ${s.eligible ? 'text-primary' : ''}`}>{metric.key === 'passing' ? `${s.passing}/${districts.length}` : s[metric.key] == null ? '—' : `${number(s[metric.key], metric.digits)}${metric.suffix}`}</strong></div>) : <span className="text-xs text-muted-foreground">Import a candidate</span>}</Panel>)}</div>
        <Panel className={best ? 'border-primary/20 bg-primary/5' : ''}><div className="flex flex-wrap items-center justify-between gap-4"><div className="flex flex-1 items-start gap-3"><CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-primary" /><div><h3 className="text-sm font-semibold">{best ? `Series ${best.source.id.toUpperCase()} meets the screening thresholds` : candidates.length ? 'Review the evidence before choosing a source' : 'Keep collected data or compare a candidate'}</h3><p className="mt-1 text-xs leading-relaxed text-muted-foreground">{best ? `${best.n} paired years; ${best.passing} of ${districts.length} reporting areas pass. Review exceptions before applying a national choice.` : 'You can retain collected data, or assign a different source to each district. Statistical fit supports your judgement; it does not establish methodological equivalence.'}</p></div></div><Button variant="outline" onClick={() => setView('district')}>Review by district</Button>{best && <Button onClick={() => assignAll(best.source.id as SourceId)}>Use Series {best.source.id.toUpperCase()} as primary</Button>}</div></Panel>
        <details className="rounded-xl border bg-card p-4 text-xs text-muted-foreground"><summary className="cursor-pointer font-medium">How these statistics are calculated</summary><p className="mt-3 leading-relaxed">R² = 1 − squared prediction error / reference variance; it may be negative. At least three paired years and non-constant reference values are required. MAPE omits zero reference values. Bias = total signed error / total absolute reference values. A missing district makes that year’s national total unavailable, rather than understating it.</p>{stats.map(s => <p className="mt-2" key={s.source.id}>Series {s.source.id.toUpperCase()}: {s.n} pairs · {number(s.coverage, 0)}% year coverage · RMSE {number(s.rmse)} {collected.unit} · {s.zeroCount} zero-reference pairs excluded from MAPE.</p>)}</details>
      </div>
    </div> : <>
      <Panel className="mb-4"><div className="flex flex-wrap items-center justify-between gap-4"><div><h3 className="text-sm font-semibold">Series selected for this exercise · {category}</h3><div className="mt-3 flex flex-wrap gap-2">{(['collected', 'a', 'b', 'mix'] as const).map(id => <Badge key={id}>{id === 'collected' ? 'Collected' : id === 'mix' ? 'Entry mix' : `Series ${id.toUpperCase()}`} · {districts.filter(d => exercise.assignments[areaKey(category, d)] === id).length}</Badge>)}<Badge tone={assigned === districts.length ? 'good' : 'warn'}>{assigned}/{districts.length} assigned</Badge></div></div><div className="flex flex-wrap gap-2"><Button variant="outline" onClick={() => assignAll('collected')}>Reset all to collected</Button><Button onClick={() => assignAll()}>Auto-assign best fit</Button></div></div></Panel>
      <div className="mb-5 flex flex-wrap items-end justify-between gap-3"><p className="max-w-lg text-sm text-muted-foreground">Choose what each district uses. Open its entries to inspect matches, fill gaps, and leave officer notes.</p><div className="flex flex-wrap items-end gap-3"><label className="flex h-10 items-center gap-2 text-xs"><input type="checkbox" checked={onlyReview} onChange={e => setOnlyReview(e.target.checked)} />Only districts needing review</label><Input aria-label="Search districts" placeholder="Search district…" className="w-44" value={search} onChange={e => setSearch(e.target.value)} /><Select label="Sort districts" value={sort} onChange={e => setSort(e.target.value)}><option value="worst">Worst fit first</option><option value="name">District name</option></Select></div></div>
      <div className="grid gap-4 md:grid-cols-2 2xl:grid-cols-4">{districtRows.map(row => <Panel className={`!p-4 ${row.good ? 'border-primary/40' : 'border-border'}`} key={row.district}><div className="flex items-center justify-between gap-2"><h3 className="font-semibold">{row.district}</h3><Badge tone={row.good ? 'good' : 'warn'}>{row.good ? 'Candidate passes' : 'Review'}</Badge></div><InventoryChart series={seriesFor(row.district)} compact />{row.matches.map(m => <p className="mt-1 font-mono text-xs text-muted-foreground" key={m.id}>Series {m.id.toUpperCase()} · R² {number(m.stats.r2)} · MAPE {number(m.stats.mape, 1)}{m.stats.mape == null ? '' : '%'} · {m.stats.n} yrs</p>)}<div className="mt-4"><Select label={`Use for ${row.district}`} value={row.choice ?? ''} onChange={e => update({ assignments: { ...exercise.assignments, [areaKey(category, row.district)]: e.target.value as SourceId | 'mix' } }, `${category} · ${row.district}: source set to ${e.target.value}`)}><option value="" disabled>Choose a source</option>{exercise.sources.filter(s => s.id !== 'surrogate').map(s => <option key={s.id} value={s.id}>{s.name}</option>)}{row.choice === 'mix' && <option value="mix">Custom entry mix</option>}</Select></div><Button variant="link" className="mt-2 h-9 px-0 text-xs" onClick={() => setEntryDistrict(row.district)}>Review entries & notes →</Button></Panel>)}</div>{!districtRows.length && <Panel>No districts match this filter. Check the search or import reference observations for this category.</Panel>}
    </>}
    <Footer back="Classification & sector" onBack={() => update({ step: 1 })} next="Continue to recalculation" onNext={() => update({ step: 3 })} disabled={!districts.length || assigned !== districts.length}>{assigned}/{districts.length} reporting areas assigned{view === 'national' && !!districts.length && <Button variant="link" size="sm" onClick={() => assignAll('collected')}>Use collected for all</Button>}</Footer>
    <SourceImport exercise={exercise} update={update} open={importOpen} onOpenChange={setImportOpen} />
  </>;
}
