import { useState } from 'react';
import { useQuery } from '@tanstack/react-query';
import { ExternalLink, Plus, Search, X } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge, Panel, Select } from '@/components/inventory/shared';
import { documentsApi } from '@/lib/api';
import { policyIssues, safeEvidenceUrl, type PolicyEvidence, type ScenarioAction } from '@/lib/scenario-analysis';
import { StanceBadge, type ScenarioProps } from './shared';
import { replaceAction, stanceLabels } from '@/lib/scenario-analysis';

export function ScenarioPolicy({ scenario: s, update }: ScenarioProps) {
  const [level, setLevel] = useState('both');
  const [lookup, setLookup] = useState<string | null>(null);
  const [query, setQuery] = useState('');
  const [submitted, setSubmitted] = useState('');
  const [manual, setManual] = useState<string | null>(null);
  const [draft, setDraft] = useState({ title: '', url: '', passage: '', level: 'national' as 'national' | 'subnational', stance: 'mentions' as PolicyEvidence['stance'] });
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const search = useQuery({ queryKey: ['scenario-policy-passages', s.countryCode, submitted], queryFn: () => documentsApi.searchPassages({ q: submitted, limit: 12 }), enabled: !!lookup && !!submitted.trim() && s.countryCode === 'UG', retry: false });
  const actions = s.actions.filter(a => a.selected);
  const changePolicy = (action: ScenarioAction, patch: Partial<ScenarioAction['policy']>, event?: string) => update({ actions: replaceAction(s, { ...action, policy: { ...action.policy, ...patch, reviewed: false } }) }, event);
  const addEvidence = (actionId: string, evidence: PolicyEvidence) => {
    const action = s.actions.find(a => a.id === actionId)!;
    if (action.policy.evidence.some(e => e.id === evidence.id)) { setNotice('This passage is already linked.'); return; }
    changePolicy(action, { evidence: [...action.policy.evidence, evidence] }, `${action.title}: linked policy evidence ${evidence.title}`); setNotice('Evidence linked. Confirm its relevance and stance on the policy card.');
  };
  const openSearch = (action: ScenarioAction) => { setLookup(action.id); setQuery(action.searchTerm); setSubmitted(action.searchTerm); setNotice(''); };
  return <>
    <header className="mb-5 flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-display text-3xl font-semibold">Does policy help or hinder each action?</h2><p className="mt-2 max-w-3xl text-sm text-muted-foreground">Link passages from Climate Policy Radar or add a local instrument, then record and confirm your assessment.</p></div><div className="flex rounded-xl bg-muted p-1">{['national', 'subnational', 'both'].map(l => <Button key={l} size="sm" variant={level === l ? 'secondary' : 'ghost'} aria-pressed={level === l} onClick={() => setLevel(l)}>{l[0].toUpperCase() + l.slice(1)}</Button>)}</div></header>
    <Panel className="mb-5 !py-4"><div className="flex flex-wrap items-center gap-x-5 gap-y-3"><span className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Recorded stance</span>{(Object.keys(stanceLabels) as PolicyEvidence['stance'][]).map(stance => <span className="flex items-center gap-2 text-xs text-muted-foreground" key={stance}><StanceBadge stance={stance} />{{ requires: 'obligation recorded', supports: 'encourages the action', restricts: 'conditions apply', forbids: 'prohibition recorded', mentions: 'no obligation assessed' }[stance]}</span>)}</div></Panel>
    <div className="space-y-4">{actions.map(action => {
      const evidence = action.policy.evidence.filter(e => level === 'both' || e.level === level);
      const constraints = action.policy.evidence.filter(e => e.stance === 'restricts' || e.stance === 'forbids');
      const open = policyIssues(action);
      return <Panel key={action.id} className={constraints.length ? 'border-orange-500/30' : ''}><div className="mb-4 flex flex-wrap items-center justify-between gap-3"><h3 className="font-semibold">{action.title}</h3><Badge tone={open.length ? 'warn' : 'good'}>{action.policy.reviewed && !open.length ? 'Assessment recorded' : constraints.length ? `${constraints.length} recorded constraints` : action.policy.evidence.length ? 'Confirm evidence & assessment' : 'No evidence recorded'}</Badge></div>
        <div className="grid gap-3 lg:grid-cols-2">{evidence.map(item => <div className="rounded-xl border bg-muted/20 p-4" key={item.id}><div className="flex items-start justify-between gap-3"><h4 className="text-sm font-semibold">{item.title}</h4><button aria-label={`Remove evidence ${item.title}`} className="rounded p-1 text-muted-foreground hover:bg-muted" onClick={() => changePolicy(action, { evidence: action.policy.evidence.filter(e => e.id !== item.id) }, `${action.title}: removed evidence ${item.title}`)}><X className="h-4 w-4" /></button></div><p className="mt-2 text-xs text-muted-foreground">{item.level} · {item.source} · {new Date(item.retrievedAt).toLocaleDateString()}{item.sample ? ' · SAMPLE' : ''}</p><p className="my-3 whitespace-pre-wrap text-sm leading-relaxed text-muted-foreground">{item.passage}</p><div className="flex flex-wrap items-end justify-between gap-3"><Select label={`Stance: ${item.title}`} value={item.stance} onChange={e => changePolicy(action, { evidence: action.policy.evidence.map(p => p.id === item.id ? { ...p, stance: e.target.value as PolicyEvidence['stance'], confirmed: false } : p) })}>{Object.entries(stanceLabels).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</Select>{item.url && safeEvidenceUrl(item.url) && <a href={item.url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 py-2 text-xs text-primary underline">Read the source<ExternalLink className="h-3 w-3" /></a>}</div><label className="mt-3 flex items-start gap-2 text-xs"><input type="checkbox" className="mt-0.5 accent-primary" checked={item.confirmed} onChange={e => changePolicy(action, { evidence: action.policy.evidence.map(p => p.id === item.id ? { ...p, confirmed: e.target.checked } : p) })} />Confirm relevance and stance: {item.title}</label></div>)}</div>
        {!evidence.length && <p className="my-4 text-sm text-muted-foreground">No {level === 'both' ? '' : `${level} `}evidence recorded. Search the corpus or add a reference. An empty search does not establish that an action is lawful or unsupported.</p>}
        <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => openSearch(action)}><Search className="mr-2 h-3 w-3" />Search policy evidence</Button><Button size="sm" variant="outline" onClick={() => { setManual(action.id); setDraft({ title: '', url: '', passage: '', level: level === 'subnational' ? 'subnational' : 'national', stance: 'mentions' }); setError(''); }}><Plus className="mr-2 h-3 w-3" />Add policy reference</Button><Button size="sm" variant={action.policy.flag === 'barrier' ? 'secondary' : 'ghost'} onClick={() => changePolicy(action, { flag: action.policy.flag === 'barrier' ? 'none' : 'barrier' }, `${action.title}: legal barrier flag changed`)}>Flag as legal barrier</Button><Button size="sm" variant={action.policy.flag === 'gap' ? 'secondary' : 'ghost'} onClick={() => changePolicy(action, { flag: action.policy.flag === 'gap' ? 'none' : 'gap' }, `${action.title}: policy gap flag changed`)}>Flag as policy gap</Button><Button size="sm" variant="link" onClick={() => update({ step: 2 })}>Adjust timing & uptake</Button></div>
        <div className="mt-5 grid gap-4 border-t pt-4 md:grid-cols-[220px_minmax(0,1fr)]"><Select label={`Scenario decision: ${action.title}`} value={action.policy.decision} onChange={e => changePolicy(action, { decision: e.target.value as ScenarioAction['policy']['decision'] })}><option value="pending">Choose a decision</option><option value="include">Include in model</option><option value="conditional">Include conditionally</option><option value="exclude">Exclude from model</option></Select><label className="text-xs font-medium text-muted-foreground">Assessment note: {action.title}<textarea className="mt-1.5 min-h-20 w-full rounded-lg border bg-background p-3 text-sm text-foreground" placeholder="Explain any uncertainty, evidence gap, reform or implementation condition assumed…" value={action.policy.note} onChange={e => changePolicy(action, { note: e.target.value })} /></label></div>
        <div className="mt-3 flex flex-wrap items-center justify-between gap-3"><p className="max-w-2xl text-xs text-muted-foreground">{open.filter(issue => issue !== 'Complete the policy review').join(' · ') || (action.policy.reviewed ? 'Assessment saved with this scenario.' : 'Confirm the evidence and record your decision.')}</p><Button size="sm" variant="outline" disabled={action.policy.reviewed || policyIssues({ ...action, policy: { ...action.policy, reviewed: true } }).length > 0} onClick={() => update({ actions: replaceAction(s, { ...action, policy: { ...action.policy, reviewed: true } }) }, `${action.title}: policy assessment confirmed (${action.policy.decision})`)}>Confirm assessment: {action.title}</Button></div>
      </Panel>;
    })}</div>
    {!actions.length && <Panel>Select actions first to review their policy evidence.</Panel>}
    <p className="mt-5 text-xs leading-relaxed text-muted-foreground">Policy search uses the app’s Uganda Climate Policy Radar export, not a live legal register. Stances are your recorded assessment of a passage. Check instrument dates, amendments, jurisdiction and applicability before relying on it; subnational evidence must be supplied separately.</p>
    <Dialog open={!!lookup} onOpenChange={open => { if (!open) setLookup(null); }}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Find policy evidence</DialogTitle><DialogDescription>Search the indexed passages and link evidence to {s.actions.find(a => a.id === lookup)?.title}. A search match is not a legal stance.</DialogDescription></DialogHeader><form className="flex gap-2" onSubmit={e => { e.preventDefault(); if (submitted === query.trim()) void search.refetch(); else setSubmitted(query.trim()); }}><Input aria-label="Policy search terms" value={query} onChange={e => setQuery(e.target.value)} placeholder="e.g. livestock, feed, biogas" /><Button type="submit" disabled={!query.trim() || s.countryCode !== 'UG'}>Search</Button></form>{s.countryCode !== 'UG' ? <p className="text-sm">This corpus covers Uganda. Add a reference for your country instead.</p> : search.isFetching ? <p role="status" className="py-4 text-sm">Searching policy passages…</p> : search.isError ? <div role="alert" className="rounded-lg border border-destructive/30 p-4 text-sm">Policy evidence could not be loaded. Your existing assessments are preserved.<Button variant="link" onClick={() => void search.refetch()}>Retry search</Button></div> : search.data && <><p className="text-xs text-muted-foreground">{search.data.total} matches · showing up to 12 · refine your search for more specific evidence</p>{search.data.passages.map(p => <div className="rounded-xl border p-4" key={p.id}><h4 className="text-sm font-semibold">{p.documentTitle ?? 'Policy passage'}</h4><p className="my-3 whitespace-pre-wrap text-sm text-muted-foreground">{p.text}</p><div className="flex items-center justify-between gap-3">{p.cprUrl && safeEvidenceUrl(p.cprUrl) && <a href={p.cprUrl} target="_blank" rel="noreferrer" className="text-xs text-primary underline">Open original document ↗</a>}<Button size="sm" variant="outline" disabled={!p.cprUrl || !safeEvidenceUrl(p.cprUrl) || s.actions.find(a => a.id === lookup)?.policy.evidence.some(e => e.id === p.id)} onClick={() => addEvidence(lookup!, { id: p.id, title: p.documentTitle ?? 'Policy passage', url: p.cprUrl!, passage: p.text, source: 'Climate Policy Radar export', level: 'national', stance: 'mentions', confirmed: false, retrievedAt: new Date().toISOString(), sample: false })}>Link passage</Button></div></div>)}{search.data.total === 0 && <p className="py-3 text-sm">No passages matched. Try broader terms or add a policy reference; absence from this corpus is not evidence of legal permission.</p>}<p className="text-xs text-muted-foreground">{search.data.attribution}</p></>}{notice && <p role="status" className="text-sm text-primary">{notice}</p>}</DialogContent></Dialog>
    <Dialog open={!!manual} onOpenChange={open => { if (!open) setManual(null); }}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>Add a policy reference</DialogTitle><DialogDescription>Record the relevant passage and a link to its source. Confirm its applicability after adding it.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e => { e.preventDefault(); if (!draft.title.trim() || !draft.passage.trim() || !safeEvidenceUrl(draft.url)) { setError('Add a title, passage and valid HTTP or HTTPS source link.'); return; } addEvidence(manual!, { ...draft, id: crypto.randomUUID(), source: 'Analyst-provided reference', confirmed: false, retrievedAt: new Date().toISOString(), sample: false }); setManual(null); }}><label className="block text-sm">Policy title<Input className="mt-1.5" value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} required /></label><label className="block text-sm">Source URL<Input type="url" className="mt-1.5" value={draft.url} onChange={e => setDraft({ ...draft, url: e.target.value })} required /></label><label className="block text-sm">Relevant passage<textarea className="mt-1.5 min-h-28 w-full rounded-lg border bg-background p-3" value={draft.passage} onChange={e => setDraft({ ...draft, passage: e.target.value })} required /></label><div className="grid grid-cols-2 gap-3"><Select label="Jurisdiction level" value={draft.level} onChange={e => setDraft({ ...draft, level: e.target.value as typeof draft.level })}><option value="national">National</option><option value="subnational">Subnational</option></Select><Select label="Recorded stance" value={draft.stance} onChange={e => setDraft({ ...draft, stance: e.target.value as typeof draft.stance })}>{Object.entries(stanceLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</Select></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button type="submit" className="w-full">Add reference</Button></form></DialogContent></Dialog>
  </>;
}
