/**
 * Collects candidate actions and their user-supplied reduction, uptake, cost, and conditionality assumptions.
 *
 * Read the owning guide before changing source, unit, authentication, or availability rules.
 */
import { useState } from 'react';
import { ArrowRight, Plus, Search, SlidersHorizontal } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge, Panel, Select } from '@/components/inventory/shared';
import { number } from '@/lib/inventory-presentation';
import { actionIssues, affectedEntries, newAction, type ScenarioAction } from '@/lib/scenario-analysis';
import type { ScenarioProps } from './shared';
import { replaceAction } from '@/lib/scenario-analysis';

export function ScenarioActions({ scenario: s, update }: ScenarioProps) {
  const [search, setSearch] = useState('');
  const [source, setSource] = useState('all');
  const [sort, setSort] = useState('reduction');
  const [showAll, setShowAll] = useState(false);
  const [editing, setEditing] = useState<ScenarioAction | null>(null);
  const [choosing, setChoosing] = useState<ScenarioAction | null>(null);
  const [error, setError] = useState('');
  const visible = s.actions.filter(a => `${a.title} ${a.description}`.toLowerCase().includes(search.toLowerCase()) && (source === 'all' || a.source === source)).sort((a, b) => Number(b.category === s.basis.category) - Number(a.category === s.basis.category) || (sort === 'name' ? a.title.localeCompare(b.title) : sort === 'cost' ? (a.costPerUnit ?? Infinity) - (b.costPerUnit ?? Infinity) : (b.reductionPct ?? -1) - (a.reductionPct ?? -1)));
  const commit = (action: ScenarioAction, event: string) => update({ actions: replaceAction(s, { ...action, policy: { ...action.policy, reviewed: false } }) }, event);
  function saveAction() {
    if (!editing.title.trim() || !editing.source.trim() || (editing.reductionPct !== null && (!Number.isFinite(editing.reductionPct) || editing.reductionPct < 0 || editing.reductionPct > 100)) || (editing.costPerUnit !== null && !Number.isFinite(editing.costPerUnit))) { setError('Add a name and source, a reduction between 0 and 100%, and a finite cost or leave it blank.'); return; }
    const next = { ...editing, title: editing.title.trim(), policy: { ...editing.policy, reviewed: false } };
    update({ actions: s.actions.some(a => a.id === editing.id) ? replaceAction(s, next) : [...s.actions, next] }, `Action assumptions saved: ${next.title}`);
    setEditing(null); setError('');
  }
  return <>
    <header className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h2 className="font-display text-3xl font-semibold">Which actions go in this scenario?</h2><p className="mt-2 text-sm text-muted-foreground">Options for {s.basis.categoryName} in {s.basis.district}, using {s.basis.entries.length} entries from your inventory.</p></div><Button variant="outline" onClick={() => { setEditing(newAction(s.basis)); setError(''); }}><Plus className="mr-2 h-4 w-4" />Add an action</Button></header>
    <div className="mb-5 flex flex-wrap items-end justify-between gap-4"><div className="flex flex-wrap items-end gap-3"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground" /><Input aria-label="Search action library" className="w-64 pl-9" placeholder="Search the library…" value={search} onChange={e => setSearch(e.target.value)} /></div><Select label="Action source" value={source} onChange={e => setSource(e.target.value)}><option value="all">All sources</option>{[...new Set(s.actions.map(a => a.source))].map(name => <option key={name}>{name}</option>)}</Select><Select label="Sort actions" value={sort} onChange={e => setSort(e.target.value)}><option value="reduction">Largest reduction %</option><option value="cost">Lowest unit cost</option><option value="name">Name</option></Select></div><span className="text-xs text-muted-foreground">Showing {Math.min(visible.length, showAll ? visible.length : 6)} of {visible.length}</span></div>
    <div className="grid items-stretch gap-4 md:grid-cols-2 xl:grid-cols-3">{visible.slice(0, showAll ? undefined : 6).map(action => {
      const other = action.category !== s.basis.category;
      const issues = actionIssues(s, action);
      return <Panel key={action.id} className={`flex flex-col ${other ? 'border-dashed bg-muted/20' : action.selected ? 'border-primary/60 ring-1 ring-primary/10' : ''}`}><div className="flex items-start justify-between gap-2"><label className="flex items-start gap-3 text-sm font-semibold"><input type="checkbox" className="mt-1 h-4 w-4 accent-primary" checked={action.selected} disabled={other} onChange={e => commit({ ...action, selected: e.target.checked }, `${e.target.checked ? 'Selected' : 'Removed'} ${action.title}`)} />{action.title}</label><Badge>{other ? 'Other category' : action.source}</Badge></div><p className="ml-7 mt-2 text-xs text-muted-foreground">{other ? `Counts in ${action.category}` : action.scope === 'whole' ? 'Whole reporting area' : `${affectedEntries(s, action).length} of ${s.basis.entries.length} entries`}</p><p className="my-4 text-sm leading-relaxed text-muted-foreground">{action.description || 'Add a description of the intervention and its emissions boundary.'}</p>
        {other ? <p className="mt-auto text-xs text-muted-foreground">Create a scenario from an inventory category matching {action.category} to include this action. It is excluded here to avoid counting effects in the wrong category.</p> : <><div className="mt-auto flex flex-wrap items-center gap-2"><div className="flex rounded-lg bg-muted p-1"><Button size="sm" variant={action.scope === 'whole' ? 'secondary' : 'ghost'} aria-pressed={action.scope === 'whole'} onClick={() => commit({ ...action, scope: 'whole' }, `${action.title}: whole reporting area`)}>Whole sector</Button><Button size="sm" variant={action.scope === 'facilities' ? 'secondary' : 'ghost'} aria-pressed={action.scope === 'facilities'} onClick={() => setChoosing({ ...action, scope: 'facilities', facilityIds: action.facilityIds.length ? action.facilityIds : s.basis.entries.map(e => e.id) })}>Per facility</Button></div>{action.scope === 'facilities' && <Button variant="link" size="sm" className="px-1" onClick={() => setChoosing(action)}>Choose entries</Button>}</div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 border-t pt-4 text-xs"><span className="font-mono">{action.reductionPct === null ? 'Effect needed' : `−${number(action.reductionPct, 1)}%`} · {action.costPerUnit === null ? 'Cost not set' : `${number(action.costPerUnit, 0)} ${s.currency}/${s.basis.unit}`}</span><Button aria-label={`Edit ${action.title}`} size="sm" variant="ghost" onClick={() => { setEditing(action); setError(''); }}><SlidersHorizontal className="mr-1 h-3 w-3" />Details</Button></div><p className="mt-2 text-xs text-muted-foreground">{action.evidence || 'No reduction evidence recorded yet.'}</p>{!!issues.length && <p className="mt-3 text-xs text-at-risk">{issues.join(' · ')}</p>}</>}
      </Panel>;
    })}</div>
    {!visible.length && <Panel>No actions match your filters. Clear the search or add your own action.</Panel>}
    {visible.length > 6 && <div className="mt-4 flex justify-end"><Button variant="link" onClick={() => setShowAll(!showAll)}>{showAll ? 'Show fewer actions' : 'Show the rest of the library'}</Button></div>}
    <p className="mt-5 text-xs leading-relaxed text-muted-foreground">Planning templates describe possible interventions. Enter a sourced reduction estimate or document your assumption before modelling. “Whole sector” applies only to the selected category and reporting area; inventory entries may represent aggregates rather than physical facilities.</p>
    <Dialog open={!!editing} onOpenChange={open => { if (!open) setEditing(null); }}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Action details & assumptions</DialogTitle><DialogDescription>Effects are relative to eligible baseline emissions at full uptake. Values are planning inputs, not verified provider estimates.</DialogDescription></DialogHeader>{editing && <form className="space-y-4" onSubmit={e => { e.preventDefault(); saveAction(); }}><label className="block text-sm">Action name<Input value={editing.title} onChange={e => setEditing({ ...editing, title: e.target.value })} className="mt-1.5" required /></label><label className="block text-sm">Description<textarea className="mt-1.5 min-h-20 w-full rounded-lg border bg-background p-3" value={editing.description} onChange={e => setEditing({ ...editing, description: e.target.value })} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Reduction at full uptake (%)<Input type="number" min={0} max={100} step="any" value={editing.reductionPct ?? ''} onChange={e => setEditing({ ...editing, reductionPct: e.target.value === '' ? null : Number(e.target.value) })} className="mt-1.5" /></label><label className="text-sm">Cost ({s.currency} / avoided {s.basis.unit})<Input type="number" step="any" value={editing.costPerUnit ?? ''} onChange={e => setEditing({ ...editing, costPerUnit: e.target.value === '' ? null : Number(e.target.value) })} className="mt-1.5" /></label></div><label className="block text-sm">Source / provider<Input className="mt-1.5" value={editing.source} onChange={e => setEditing({ ...editing, source: e.target.value })} required /></label><label className="block text-sm">Evidence or assumption<textarea className="mt-1.5 min-h-20 w-full rounded-lg border bg-background p-3" placeholder="Source, publication date, applicability and uncertainty; or label an analyst assumption." value={editing.evidence} onChange={e => setEditing({ ...editing, evidence: e.target.value })} /></label><label className="block text-sm">Policy search terms<Input className="mt-1.5" value={editing.searchTerm} onChange={e => setEditing({ ...editing, searchTerm: e.target.value })} /></label>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button type="submit" className="w-full">Save action details<ArrowRight className="ml-2 h-4 w-4" /></Button></form>}</DialogContent></Dialog>
    <Dialog open={!!choosing} onOpenChange={open => { if (!open) setChoosing(null); }}><DialogContent className="max-h-[85dvh] overflow-y-auto"><DialogHeader><DialogTitle>Choose eligible inventory entries</DialogTitle><DialogDescription>{choosing?.title} · {s.basis.district}. Confirm applicability before selecting an entry.</DialogDescription></DialogHeader>{choosing && <><div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setChoosing({ ...choosing, facilityIds: s.basis.entries.map(e => e.id) })}>Select all</Button><Button variant="ghost" size="sm" onClick={() => setChoosing({ ...choosing, facilityIds: [] })}>Clear</Button></div><div className="max-h-80 space-y-2 overflow-auto">{s.basis.entries.map(entry => <label className="flex items-start gap-3 rounded-lg border p-3 text-sm" key={entry.id}><input type="checkbox" className="mt-1 accent-primary" checked={choosing.facilityIds.includes(entry.id)} onChange={e => setChoosing({ ...choosing, facilityIds: e.target.checked ? [...choosing.facilityIds, entry.id] : choosing.facilityIds.filter(id => id !== entry.id) })} /><span>{entry.name}<span className="mt-1 block text-xs text-muted-foreground">{entry.id} · {number(entry.value)} {s.basis.unit} · {entry.source}</span></span></label>)}</div><Button disabled={!choosing.facilityIds.length} onClick={() => { commit({ ...choosing, scope: 'facilities' }, `${choosing.title}: selected ${choosing.facilityIds.length} inventory entries`); setChoosing(null); }}>Use {choosing.facilityIds.length} entries</Button></>}</DialogContent></Dialog>
  </>;
}
