/**
 * Explains the deterministic scenario result, allocated action effects, assumptions, and audit history.
 *
 * Read the owning guide before changing source, unit, authentication, or availability rules.
 */
import { useState } from 'react';
import { Download, Settings2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Badge, Panel } from '@/components/inventory/shared';
import { InventoryChart } from '@/components/inventory/InventoryChart';
import { downloadChart, number } from '@/lib/inventory-presentation';
import { downloadFile, seriesCsv } from '@/lib/inventory-workspace';
import { calculateScenario, scenarioReadiness, scenarioExport } from '@/lib/scenario-analysis';
import type { ScenarioProps } from './shared';

export function ScenarioAssumptions({ scenario: s, update, open, onClose }: ScenarioProps & { open: boolean; onClose: () => void }) {
  const [draft, setDraft] = useState({ horizon: String(s.horizon), growth: String(s.annualGrowthPct), target: s.targetValue === null ? '' : String(s.targetValue), source: s.targetSource, note: s.assumptionNote, currency: s.currency });
  const [error, setError] = useState('');
  return <Dialog open={open} onOpenChange={v => { if (!v) onClose(); }}><DialogContent className="max-h-[90dvh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Projection assumptions</DialogTitle><DialogDescription>The baseline is pinned to {s.basis.year}. Growth, costs and the target below are analyst inputs for this scenario.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={e => {
    e.preventDefault(); const horizon = Number(draft.horizon), growth = Number(draft.growth), target = draft.target.trim() ? Number(draft.target) : null;
    if (!draft.horizon.trim() || !Number.isInteger(horizon) || horizon <= s.basis.year || horizon > Math.min(2250, s.basis.year + 50) || !draft.growth.trim() || !Number.isFinite(growth) || growth < -99 || growth > 100 || (target !== null && (!Number.isFinite(target) || target < 0)) || !draft.currency.trim()) { setError('Check the projection horizon, growth (−99% to 100%), non-negative target and currency.'); return; }
    if (s.actions.some(a => a.start > horizon || Object.values(a.starts).some(y => y > horizon))) { setError('Move action start years inside the new horizon before shortening it.'); return; }
    update({ horizon, annualGrowthPct: growth, targetValue: target, targetSource: draft.source, assumptionNote: draft.note, currency: draft.currency.trim() }, 'Projection assumptions updated'); onClose();
  }}><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm">Horizon year<Input className="mt-1.5" type="number" min={s.basis.year + 1} max={Math.min(2250, s.basis.year + 50)} value={draft.horizon} onChange={e => setDraft({ ...draft, horizon: e.target.value })} /></label><label className="text-sm">Annual BAU growth (%)<Input className="mt-1.5" type="number" min={-99} max={100} step="any" value={draft.growth} onChange={e => setDraft({ ...draft, growth: e.target.value })} /></label></div><label className="block text-sm">BAU rationale<textarea className="mt-1.5 min-h-20 w-full rounded-lg border bg-background p-3" value={draft.note} onChange={e => setDraft({ ...draft, note: e.target.value })} placeholder="Explain the assumed growth rate and cite evidence where available." /></label><label className="block text-sm">Target in {s.basis.unit} (optional)<Input type="number" min={0} step="any" className="mt-1.5" value={draft.target} onChange={e => setDraft({ ...draft, target: e.target.value })} /></label><label className="block text-sm">Target source / allocation rationale<Input className="mt-1.5" value={draft.source} onChange={e => setDraft({ ...draft, source: e.target.value })} placeholder="Document the category/district allocation or label an analyst target." /></label><label className="block text-sm">Cost currency<Input className="mt-1.5" value={draft.currency} maxLength={20} onChange={e => setDraft({ ...draft, currency: e.target.value })} /></label><p className="text-xs text-muted-foreground">Changing the currency label does not convert costs. All action costs must be entered in the same currency per avoided {s.basis.unit}. This model excludes capital schedules and discounting.</p>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button type="submit" className="w-full">Apply projection assumptions</Button></form></DialogContent></Dialog>;
}
export function ScenarioResult({ scenario: s, update, onSettings }: ScenarioProps & { onSettings: () => void }) {
  const [whole, setWhole] = useState(false);
  const result = calculateScenario(s);
  const issues = scenarioReadiness(s);
  const actions = s.actions.filter(a => a.selected);
  const gaps = actions.filter(a => a.policy.flag === 'gap' || !a.policy.evidence.length).length;
  const constrained = actions.filter(a => a.policy.decision === 'conditional' || a.policy.flag === 'barrier').length;
  const series = [{ id: 'collected', name: 'Business as usual', color: 'hsl(var(--chart-2))', points: result.rows.map(r => ({ year: r.year, value: r.bau })) }, { id: 'scenario', name: 'With these actions', color: 'hsl(var(--chart-1))', points: result.rows.map(r => ({ year: r.year, value: r.withActions })) }, ...(s.targetValue === null ? [] : [{ id: 'b', name: 'Target benchmark', color: 'hsl(var(--chart-3))', points: result.rows.map(r => ({ year: r.year, value: r.target })) }])];
  return <>
    <header className="mb-6 flex flex-wrap items-end justify-between gap-3"><div><h2 className="font-display text-3xl font-semibold">{s.name}</h2><p className="mt-2 text-sm text-muted-foreground">{s.basis.category} {s.basis.categoryName} · {s.basis.district} · {actions.length} actions · against the pinned inventory</p></div><Button variant="outline" onClick={onSettings}><Settings2 className="mr-2 h-4 w-4" />Projection assumptions</Button></header>
    <Panel><div className="mb-3 flex flex-wrap items-center justify-between gap-3"><p className="text-xs text-muted-foreground">Annual emissions · {s.basis.unit} · {s.annualGrowthPct}% assumed annual BAU growth</p><Badge tone={issues.length ? 'warn' : 'good'}>{issues.length ? 'Preview · review incomplete' : s.savedAt ? 'Saved scenario' : 'Ready to save'}</Badge></div><div id="scenario-result-chart"><InventoryChart series={series} unit={s.basis.unit} /></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3 border-t pt-3"><p className="max-w-2xl text-xs text-muted-foreground">{s.targetValue === null ? 'No target entered. Add a category- and area-specific benchmark to measure the gap.' : `${s.horizon} target: ${number(s.targetValue)} ${s.basis.unit} · ${s.targetSource || 'Source not recorded'}. The horizontal line is an endpoint benchmark, not a prescribed trajectory.`}</p><Button variant="ghost" size="sm" onClick={() => downloadChart('scenario-result-chart', `${s.basis.sample ? 'SAMPLE · ' : ''}${s.name} · ${s.basis.unit}`, series, 'scenario-result.svg')}>Export chart</Button></div></Panel>
    <div className="mt-4 grid grid-cols-2 gap-4 xl:grid-cols-4">{[{ label: `Below BAU in ${s.horizon}`, value: `${number(result.reductionPct, 1)}%`, hint: `${number(result.latest.reduction)} ${s.basis.unit} avoided` }, { label: 'Cumulative saving', value: number(result.cumulative), hint: `${s.basis.unit} · ${s.basis.year + 1}–${s.horizon}` }, { label: result.targetGap === null ? 'Target gap' : result.targetGap > 0 ? 'Still short of target' : 'Target reached in model', value: result.targetGap === null ? 'Not set' : number(result.targetGap), hint: s.basis.unit }, { label: 'Average abatement cost', value: result.averageCost === null ? 'Not available' : number(result.averageCost), hint: `${s.currency} / avoided ${s.basis.unit}` }].map(metric => <Panel className="!p-5" key={metric.label}><p className="text-xs font-medium text-muted-foreground">{metric.label}</p><p className="my-3 break-words font-mono text-2xl font-semibold">{metric.value}</p><p className="text-xs text-muted-foreground">{metric.hint}</p></Panel>)}</div>
    <Panel className="mt-4 border-primary/20 bg-primary/5"><div className="flex flex-wrap items-center justify-between gap-4"><div className="max-w-3xl text-sm leading-relaxed"><p>{result.targetGap == null ? 'Set a target benchmark to assess how much more reduction is needed.' : result.targetGap > 0 ? `These actions leave ${number(result.targetGap)} ${s.basis.unit} above the ${s.horizon} target. Explore another action or a faster rollout to narrow the gap.` : 'These assumptions meet the target benchmark in the model. Confirm feasibility and evidence before using the result for planning.'}</p><p className="mt-2 text-xs text-muted-foreground">{gaps} actions have a policy evidence gap · {constrained} have conditional assumptions or barrier flags · {result.overlapCount} entries have overlapping actions.</p></div><div className="flex gap-2"><Button variant="link" onClick={() => update({ step: 1 })}>Add an action</Button><Button variant="link" onClick={() => update({ step: 3 })}>Review the gap</Button></div></div></Panel>
    {issues.length > 0 && <Panel className="mt-4 border-border"><h3 className="text-sm font-semibold">Open items before saving the result</h3><ul className="mt-3 list-disc space-y-1 pl-5 text-xs text-muted-foreground">{issues.map((issue, index) => <li key={index}>{issue}</li>)}</ul></Panel>}
    <div className="mt-5 flex flex-wrap items-center justify-between gap-2"><Button variant="link" onClick={() => setWhole(!whole)}>{whole ? 'Hide scenario details' : 'See the whole scenario'}</Button><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={() => downloadFile('scenario-annual-results.csv', seriesCsv(result.rows.map(row => ({ scenario: s.name, sample: s.basis.sample, category: s.basis.category, district: s.basis.district, unit: s.basis.unit, currency: s.currency, ...row }))), 'text/csv')}><Download className="mr-2 h-3 w-3" />Export annual results</Button><Button variant="outline" size="sm" onClick={() => downloadFile('scenario-analysis.json', JSON.stringify(scenarioExport(s), null, 2))}>Export full scenario</Button></div></div>
    {whole && <div className="mt-4 space-y-4"><Panel><h3 className="mb-4 font-semibold">Action contributions after overlap adjustment</h3><div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="border-b text-xs text-muted-foreground"><tr>{['Action', 'Decision', `${s.horizon} reduction`, 'Cumulative saving', `Cost (${s.currency})`].map(t => <th className="p-2 font-medium" scope="col" key={t}>{t}</th>)}</tr></thead><tbody>{actions.map(a => <tr className="border-b last:border-0" key={a.id}><td className="p-2">{a.title}</td><td className="p-2 text-xs">{a.policy.decision}</td><td className="p-2 font-mono">{number(result.effects[a.id].annual)}</td><td className="p-2 font-mono">{number(result.effects[a.id].cumulative)}</td><td className="p-2 font-mono">{number(result.effects[a.id].cost)}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-muted-foreground">Savings in {s.basis.unit}. Combined savings are allocated in proportion to each action’s standalone reduction fraction. Costs follow those allocated savings; missing cost inputs remain unavailable.</p></Panel><Panel><h3 className="mb-3 font-semibold">Pinned inventory & assumptions</h3><p className="text-sm">{s.basis.exerciseName} · {s.basis.categoryName} · {s.basis.district} · {s.basis.year}</p><p className="mt-2 text-xs text-muted-foreground">{s.basis.measurementBasis} · method: {s.basis.method} · pinned exercise revision {new Date(s.basis.exerciseUpdatedAt).toLocaleString()}</p><p className="mt-3 whitespace-pre-wrap text-sm text-muted-foreground">{s.assumptionNote || 'No BAU rationale recorded.'}</p><p className="mt-3 text-xs text-muted-foreground">Model: baseline × (1 + growth)ⁿ; remaining emissions × product(1 − reduction × uptake) at each entry. Conditional actions are included as stated assumptions. Policy exclusions contribute zero. This is a deterministic planning model without uncertainty intervals or an automatic forecast.</p></Panel><Panel><h3 className="mb-3 font-semibold">Scenario history</h3><ol className="max-h-64 space-y-3 overflow-auto">{[...s.audit].reverse().map((event, i) => <li key={i} className="border-l-2 border-primary/20 pl-3"><p className="text-xs text-muted-foreground">{new Date(event.at).toLocaleString()}</p><p className="mt-1 text-sm">{event.action}</p></li>)}</ol></Panel></div>}
  </>;
}
