/**
 * Screen: exports and reporting formats.
 *
 * Produces the files needed for official reporting — the CRT/BTR formats used in
 * UN climate submissions — plus Excel and PDF versions for ordinary use. Each
 * export records which view it was taken from, so a file can be traced back to
 * what was on screen.
 */
import { exportRecords, getActor } from "@/data/uganda-strategy-data";
// Export helpers load on demand — they pull in the PDF/spreadsheet libraries
// (~235 kB), which no visitor should download unless they actually export.
import { useEmissionsData } from "@/context/EmissionsDataContext";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { toast } from "sonner";

export default function ExportsAPI() {
  const emissions = useEmissionsData();
  const geoLabel =
    emissions.geography === "district" && emissions.districtName
      ? emissions.districtName
      : "national";
  return (
    <ScrollArea className="h-full">
      <div className="p-4 space-y-4 max-w-4xl">
        <h2 className="text-lg font-bold text-foreground">Exports & API</h2>
        <p className="text-xs text-muted-foreground">CRT/BTR CSV exporter, OpenAPI stubs, and webhook placeholders.</p>

        {/* CRT/BTR Export */}
        <Card>
          <CardContent className="p-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">CRT/BTR Export</h3>
            <p className="text-[10px] text-muted-foreground mb-2">
              Export NDC targets, observed emissions, progress, and provenance for the current geography
              (<span className="font-medium text-foreground">{geoLabel}</span>) as a CRT/BTR-style CSV for biennial
              reporting prep. This is an illustrative layout, not a UNFCCC ETF-validated Common Reporting Table.
            </p>
            <div className="flex gap-2">
              <Button size="sm" className="text-xs" onClick={async () => {
                await (await import("@/lib/ndc-export")).exportCrtBtrCsv(emissions);
                toast.success(`CRT/BTR CSV exported (${geoLabel})`);
              }}>Export CRT/BTR CSV</Button>
              <Button size="sm" variant="outline" className="text-xs" onClick={async () => {
                await (await import("@/lib/ndc-export")).exportNdcDashboardPdf(emissions);
                toast.success(`BTR summary PDF exported (${geoLabel})`);
              }}>Export BTR Summary PDF</Button>
            </div>
          </CardContent>
        </Card>

        {/* Export history */}
        <Card>
          <CardContent className="p-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">Export History</h3>
            <table className="w-full text-[10px]">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-1 px-1 font-semibold text-muted-foreground">Type</th>
                  <th className="text-left py-1 px-1 font-semibold text-muted-foreground">Filters</th>
                  <th className="text-left py-1 px-1 font-semibold text-muted-foreground">Generated By</th>
                  <th className="text-left py-1 px-1 font-semibold text-muted-foreground">Date</th>
                </tr>
              </thead>
              <tbody>
                {exportRecords.map(exp => {
                  const actor = getActor(exp.generated_by);
                  return (
                    <tr key={exp.id} className="border-b border-border/30">
                      <td className="py-1 px-1"><Badge variant="outline" className="text-[9px] h-4">{exp.export_type}</Badge></td>
                      <td className="py-1 px-1 text-muted-foreground">{Object.entries(exp.filter_params).map(([k, v]) => `${k}=${v}`).join(", ")}</td>
                      <td className="py-1 px-1">{actor?.display_name ?? exp.generated_by}</td>
                      <td className="py-1 px-1 text-muted-foreground">{new Date(exp.generated_at).toLocaleDateString()}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </CardContent>
        </Card>

        {/* OpenAPI Stub */}
        <Card>
          <CardContent className="p-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">OpenAPI JSON Stub</h3>
            <p className="text-[10px] text-muted-foreground mb-2">Live emissions endpoints served by the Express API (Climate TRACE backed). National (<code>gadm_id=UGA</code>) and district (<code>gadm_id=UGA.&lt;n&gt;_1</code> or <code>district=&lt;name&gt;</code>) geographies are supported.</p>
            <pre className="text-[9px] font-mono bg-muted p-2 rounded overflow-x-auto max-h-[200px]">
{`{
  "openapi": "3.0.3",
  "info": { "title": "Uganda NDC Emissions API", "version": "1.0.0" },
  "paths": {
    "/api/v1/emissions/dashboard": { "get": { "summary": "Dashboard (params: since, to, gadm_id|district)" } },
    "/api/v1/emissions/timeseries": { "get": { "summary": "Sector timeseries (params: sector, gadm_id|district)" } },
    "/api/v1/emissions/progress": { "get": { "summary": "Sector progress vs NDC (params: sector, gadm_id|district)" } },
    "/api/v1/emissions/districts": { "get": { "summary": "List mapped Uganda districts (GADM)" } },
    "/api/v1/emissions/sources": { "get": { "summary": "Asset/source-level emitters (params: gadm_id|district, year, limit, offset)" } },
    "/api/v1/emissions/trackability": { "get": { "summary": "NDC measurable-variable trackability (params: country)" } },
    "/api/v1/emissions/summary": { "get": { "summary": "On/off-track sector counts" } },
    "/api/v1/health": { "get": { "summary": "Climate TRACE API health + cache stats" } }
  }
}`}
            </pre>
          </CardContent>
        </Card>

        {/* Webhook stubs */}
        <Card>
          <CardContent className="p-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">Webhook Placeholders</h3>
            <div className="space-y-1">
              {[
                { endpoint: "/api/npa/pull", desc: "Pull programme M&E data from NPA" },
                { endpoint: "/api/ubos/push", desc: "Receive push updates from UBOS statistics" },
                { endpoint: "/api/mofped/budget", desc: "Sync budget code alignment from MoFPED" },
              ].map(wh => (
                <div key={wh.endpoint} className="flex items-center justify-between py-1 border-b border-border/30 last:border-0">
                  <code className="text-[10px] font-mono text-foreground">{wh.endpoint}</code>
                  <span className="text-[10px] text-muted-foreground">{wh.desc}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </ScrollArea>
  );
}
