import { exportRecords, kpis, strategies, getActor } from "@/data/uganda-strategy-data";
import { exportToExcel, exportToPDF } from "@/lib/export";
import { Card, CardContent } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { toast } from "sonner";

export default function ExportsAPI() {
  return (
    <ScrollArea className="h-full">
      <div className="p-4 space-y-4 max-w-4xl">
        <h2 className="text-lg font-bold text-foreground">Exports & API</h2>
        <p className="text-xs text-muted-foreground">CRT/BTR CSV exporter, OpenAPI stubs, and webhook placeholders.</p>

        {/* CRT/BTR Export */}
        <Card>
          <CardContent className="p-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">CRT/BTR Export</h3>
            <p className="text-[10px] text-muted-foreground mb-2">
              Export NDC activity data, activity-level emissions, progress, and provenance into ETF-compliant Common Reporting Table rows.
              BTR bundles CRTs + narrative summary + metadata for biennial submission.
            </p>
            <div className="flex gap-2">
              <Button size="sm" className="text-xs" onClick={() => {
                exportToExcel();
                toast.success("CRT data exported as Excel (CRT format pending full ETF schema)");
              }}>Export CRT CSV</Button>
              <Button size="sm" variant="outline" className="text-xs" onClick={() => {
                exportToPDF();
                toast.success("BTR summary PDF exported");
              }}>Export BTR Summary PDF</Button>
            </div>
          </CardContent>
        </Card>

        {/* Export history */}
        <Card>
          <CardContent className="p-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">Export History</h3>
            <table className="w-full text-[10px]">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left py-1 px-1 font-semibold text-muted-foreground">Type</th>
                  <th className="text-left py-1 px-1 font-semibold text-muted-foreground">Filters</th>
                  <th className="text-left py-1 px-1 font-semibold text-muted-foreground">Generated By</th>
                  <th className="text-left py-1 px-1 font-semibold text-muted-foreground">Date</th>
                </tr>
              </thead>
              <tbody>
                {exportRecords.map(exp => {
                  const actor = getActor(exp.generated_by);
                  return (
                    <tr key={exp.id} className="border-b border-border/30">
                      <td className="py-1 px-1"><Badge variant="outline" className="text-[9px] h-4">{exp.export_type}</Badge></td>
                      <td className="py-1 px-1 text-muted-foreground">{Object.entries(exp.filter_params).map(([k, v]) => `${k}=${v}`).join(", ")}</td>
                      <td className="py-1 px-1">{actor?.display_name ?? exp.generated_by}</td>
                      <td className="py-1 px-1 text-muted-foreground">{new Date(exp.generated_at).toLocaleDateString()}</td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </CardContent>
        </Card>

        {/* OpenAPI Stub */}
        <Card>
          <CardContent className="p-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">OpenAPI JSON Stub</h3>
            <p className="text-[10px] text-muted-foreground mb-2">Auto-generated from data model. Collections: strategies, programmes, activities, kpis, progress, actors, data_sources, projections, exports.</p>
            <pre className="text-[9px] font-mono bg-muted p-2 rounded overflow-x-auto max-h-[200px]">
{`{
  "openapi": "3.0.3",
  "info": { "title": "Uganda NDC & Strategy API", "version": "1.0.0" },
  "paths": {
    "/api/strategies": { "get": { "summary": "List strategies" } },
    "/api/programmes": { "get": { "summary": "List NDP IV programmes" } },
    "/api/activities": { "get": { "summary": "List activities" } },
    "/api/kpis": { "get": { "summary": "List KPIs & proxies" } },
    "/api/progress": { "get": { "summary": "List progress records" } },
    "/api/actors": { "get": { "summary": "List actors & focal points" } },
    "/api/projections": { "get": { "summary": "List projection scenarios" } },
    "/api/exports": { "post": { "summary": "Generate CRT/BTR export" } }
  }
}`}
            </pre>
          </CardContent>
        </Card>

        {/* Webhook stubs */}
        <Card>
          <CardContent className="p-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-muted-foreground mb-2">Webhook Placeholders</h3>
            <div className="space-y-1">
              {[
                { endpoint: "/api/npa/pull", desc: "Pull programme M&E data from NPA" },
                { endpoint: "/api/ubos/push", desc: "Receive push updates from UBOS statistics" },
                { endpoint: "/api/mofped/budget", desc: "Sync budget code alignment from MoFPED" },
              ].map(wh => (
                <div key={wh.endpoint} className="flex items-center justify-between py-1 border-b border-border/30 last:border-0">
                  <code className="text-[10px] font-mono text-foreground">{wh.endpoint}</code>
                  <span className="text-[10px] text-muted-foreground">{wh.desc}</span>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </ScrollArea>
  );
}
